### ISSUE TITLE
Restructure doc into smaller documents with table of contents tying it all up

### ISSUE THREAD

**Issue by olasitarska** [olasitarska/coc-incident-process#6]
I think it'd be easier to link to / browse if it's a couple of smaller documents divided by sections that just one big page

**Comment by olasitarska** [comment]
As a first step for this, I added SUMMARY.md (to hold table of contents) and uploaded everything to Gitbook for easy reading: https://olasitarska.gitbooks.io/coc-incident-process/content/

Gitbook will autoupdate based on master.

**Comment by olasitarska** [comment]
Came up with initial structure like this one below. The main headers are chapters in Gitbook, and only "Response to reports" chapter has subchapters. 

@bmispelon @asendecka any thoughts?

Introduction
- What this document is
- How to use it
- Disclaimers
- Thanks & acknowledgements 

Preparation & training for your team
- Current "be prepare" section
- Current "training section"

Code of Conduct visibility
- Advise from our transparency report on how to make CoC visible
- Guidance on what should be on the CoC page
- Guidance on what should be on the posters
- Guidance where to link to CoC page

Structure of the team
- How ideal CoC team should look like, what are the roles
- Does conf Chair needs to be a part of the team?

Receiving reports
- What are the ways you're gonna receive reports 
- Current "Receiving report" section

Response to reports
- First page should be just point by point process with one sentence explanation and linking to specific subsections:
  - 1. Initial response to report
  - 2. CoC team meeting
  - 3. Writing up an internal report
  - 4. Making a decision of possible sanctions, deciding who is going to "do the talk"
    - 4.1. What are the possible sanctions?
  - 5. Having "the talk"
    - 5.1. Guidance on giving warnings
  - 6. CoC team meeting & followup emails to everyone involved
  - 7. Communication (with and outside involved people). Whom to inform? In what way?
  - 8. Both internal, and to the DSF
  - 9. During & post-event transparency
  - 10. Things to avoid, what not to do 

Data retention
- How to store data safely?
- Who should be able to access them?

Inclusivity
- Code of Conduct is about making people feel comfortable. What are the other ways to make your event more comfortable for your attendees?
  - Quiet room
  - Prayer room
  - Bathroom gender signs
  - Bathroom baskets
  - Photography policy
  - Childcare
  - Accessibility of the venue
  - Diet requirements & proper labeling
  - Live captioning

Templates
- Email templates
- Transparency report templates
- Internal report template
- Tracking spreadsheet template

**Comment by asendecka** [comment]
That looks very good. Let's split the content we have into bits as the table of content above suggest and then fill in the missing chapters. Happy to start working on that tomorrow :).
